package ru.geekbrains.db.model;

public class Categories {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbggenerated Sat Dec 18 21:17:47 MSK 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.title
     *
     * @mbggenerated Sat Dec 18 21:17:47 MSK 2021
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.id
     *
     * @return the value of categories.id
     *
     * @mbggenerated Sat Dec 18 21:17:47 MSK 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.id
     *
     * @param id the value for categories.id
     *
     * @mbggenerated Sat Dec 18 21:17:47 MSK 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.title
     *
     * @return the value of categories.title
     *
     * @mbggenerated Sat Dec 18 21:17:47 MSK 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.title
     *
     * @param title the value for categories.title
     *
     * @mbggenerated Sat Dec 18 21:17:47 MSK 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}